version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "kathmandu777"
      - "lemonadern"
    assignees:
      - "kathmandu777"
    open-pull-requests-limit: 5
    target-branch: "master"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "dependabot"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "kathmandu777"
      - "lemonadern"
    assignees:
      - "kathmandu777"
    open-pull-requests-limit: 5
    target-branch: "master"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "dependabot"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "kathmandu777"
      - "lemonadern"
    assignees:
      - "kathmandu777"
    open-pull-requests-limit: 5
    target-branch: "master"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "dependabot"

  - package-ecosystem: "pip"
    directory: "/django"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - "kathmandu777"
      - "lemonadern"
    assignees:
      - "kathmandu777"
    open-pull-requests-limit: 5
    target-branch: "master"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "dependabot"
 