version: "3.7"
services:
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - 8000:8000
    env_file: ./fastapi/fastapi.env
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./postgres/postgres.env
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    tty: true
    volumes:
      - pgadmin4_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin4_data:
