version: "3.7"
services:
  django:
    # ビルドするdockerファイルが格納されたディレクトリ
    build: ./django
    volumes:
      # マウントするディレクトリ
      - ./django:/code
      - ./django/static:/code/static
    expose:
      - 8000
    env_file:
      # 環境変数に設定するファイル
      - ./django/.env
    depends_on:
      # 接続するサービス
      - postgres
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - ./django/static:/app/static
      # node_modulesをdata volumeで保持
      - /app/node_modules
  postgres:
    build: ./postgres
    volumes:
      # DBのデータはボリュームを作成して保存
      # ディレクトリとマウントとって実データをホストOSに直接残しても良い
      # /var/lib/postgresql/dataにDBのデータが格納されている
      - postgres_data:/var/lib/postgresql/data
    env_file: ./postgres/.env
    ports:
      # ホスト側のポートはローカルのpsqlとバッティングするので5432以外にする
      - 5433:5432
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - django
    volumes:
      - ./django/static:/code/static
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
volumes:
  postgres_data:
