# Generated by Django 3.2.4 on 2021-08-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekigae', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_sheet_id',
            new_name='student_sheet',
        ),
        migrations.RenameField(
            model_name='studentsheet',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('number', 'student_sheet'), name='student_number_unique'),
        ),
    ]
