# Generated by Django 3.2.4 on 2021-08-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekigae', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatformat',
            options={'verbose_name': 'seat format', 'verbose_name_plural': 'seat formats'},
        ),
        migrations.AlterModelOptions(
            name='studentsheet',
            options={'verbose_name': 'student sheet', 'verbose_name_plural': 'student sheets'},
        ),
    ]
