# Generated by Django 3.2.7 on 2021-09-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sekigae", "0002_auto_20210918_0740"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seatpair",
            options={"verbose_name": "seat pair", "verbose_name_plural": "seat pairs"},
        ),
        migrations.AlterModelOptions(
            name="seatsheet",
            options={"verbose_name": "seat sheet", "verbose_name_plural": "seat sheets"},
        ),
    ]
